name: 🥯 Bun Release

on:
  release:
    types: [published]

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: 🏗️ Build
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.setver.outputs.version }}

    steps:
      - name: 🧾 Checkout source
        uses: actions/checkout@v3

      - name: 🏷️ Set release version
        id: setver
        run: |
          VERSION="${GITHUB_REF#refs/tags/v}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: 📦 Create .choco.pkg
        run: |
          mkdir -p release
          tar -czf "release/${{ vars.NAME }}-${VERSION}.choco.pkg" *

      - name: 📤 Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: choco-pkg
          path: release/${{ vars.NAME }}-${{ steps.setver.outputs.version }}.choco.pkg

  release:
    name: 📤 Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: 🧾 Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: choco-pkg
          path: release

      - name: 📤 Upload Package to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/${{ vars.NAME }}-${{ needs.build.outputs.version }}.choco.pkg
